---
openapi: 3.0.1
info:
  title: Re:Start API
  description: Restart 서비스를 위한 Swagger UI 입니다.
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: MetaData API
  description: 메타 데이터 API 입니다.
paths:
  "/api/v1/meta/Region":
    get:
      tags:
      - MetaData API
      summary: Region List 조회
      description: 지역 List 정보를 조회합니다.
      operationId: getRegionList
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/RegionListResponseDTO"
  "/api/v1/meta/Position":
    get:
      tags:
      - MetaData API
      summary: Position List 조회
      description: 직무 List 정보를 조회합니다.
      operationId: getPositionList
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PositionListResponseDTO"
  "/api/v1/meta/PositionCategory":
    get:
      tags:
      - MetaData API
      summary: PositionCategory List 조회
      description: 직무 카테고리 List 정보를 조회합니다.
      operationId: getPositionCategoryList
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PositionCategoryListResponseDTO"
  "/api/v1/meta/HighestLevelEducation":
    get:
      tags:
      - MetaData API
      summary: Highest Level of Education List 조회
      description: 최종학력 List 정보를 조회합니다.
      operationId: getEducationList
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/EducationListResponseDTO"
  "/api/v1/meta/Benefit":
    get:
      tags:
      - MetaData API
      summary: Benefit List 조회
      description: 복리후생 List 정보를 조회합니다.
      operationId: getBenefitList
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/BenefitListResponseDTO"
  "/api/v1/meta/BenefitCategory":
    get:
      tags:
      - MetaData API
      summary: BenefitCategory List 조회
      description: 복리후생 카테고리 List 정보를 조회합니다.
      operationId: getBenefitCategoryList
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/BenefitCategoryListResponseDTO"
components:
  schemas:
    Region:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    RegionListResponseDTO:
      type: object
      properties:
        list:
          type: array
          items:
            "$ref": "#/components/schemas/Region"
    Position:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          "$ref": "#/components/schemas/PositionCategory"
    PositionCategory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    PositionListResponseDTO:
      type: object
      properties:
        list:
          type: array
          items:
            "$ref": "#/components/schemas/Position"
    PositionCategoryListResponseDTO:
      type: object
      properties:
        list:
          type: array
          items:
            "$ref": "#/components/schemas/PositionCategory"
    EducationListResponseDTO:
      type: object
      properties:
        list:
          type: array
          items:
            "$ref": "#/components/schemas/HighestLevelEducation"
    HighestLevelEducation:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    BenefitListResponseDTO:
      type: object
      properties:
        list:
          type: array
          items:
            "$ref": "#/components/schemas/EmployeeBenefit"
    EmployeeBenefit:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          "$ref": "#/components/schemas/EmployeeBenefitsCategory"
    EmployeeBenefitsCategory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    BenefitCategoryListResponseDTO:
      type: object
      properties:
        list:
          type: array
          items:
            "$ref": "#/components/schemas/EmployeeBenefitsCategory"
